name: Build and Upload to Cachix

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kernel: [ linux_6_12, linux_6_18, linux_7_0, linux_default, linux_latest, linux_rpi1, linux_rpi2, linux_rpi3, linux_rpi4, linux_testing, linux_xanmod, linux_xanmod_latest, linux_xanmod_stable, linux_zen ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Enable Cachix
        uses: cachix/cachix-action@v15
        with:
          name: nixos-linux-rt
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build kernel
        run: nix build .#legacyPackages.x86_64-linux.kernels.${{ matrix.kernel }} --no-link
