name: Build and Upload to Cachix

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kernel: []

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Enable Cachix
        uses: cachix/cachix-action@v15
        with:
          name: nixos-linux-rt
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build kernel
        run: nix build .#legacyPackages.x86_64-linux.kernels.${{ matrix.kernel }} --no-link
